# Generated by Django 5.1 on 2024-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
